#!/bin/sh

# Setup symlinks
# Be careful of running this script, this will destroy  your current vim files
mv  ~/.vim ~/.vim.bk
mv  ~/.vimrc ~/.vimrc.bk

ln -s  ~/dotfiles/vim-helper/.vimrc ~/.vimrc
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
